### PR TITLE
Add my doom emacs icon.

### PR DESCRIPTION
**Pull request by wildwestrom**
Hi there, I just created a new icon. 
It's doom themed for those who prefer doom emacs. 
Let me know if you like it.

### CODE REVIEW

**Review by d12frosted — APPROVED** [review]
Absolutely! I love it!

**Comment by wildwestrom** [comment]
Awesome! Glad you like it!
I hope other people get inspired to make other doom themed emacs icons.

**Comment by d12frosted** [comment]
Thank you for your contribution! Merged as a869018. 🎉

**Comment by daviderestivo** [comment]
@wildwestrom is it ok if I add the same icon to [emacs-head](https://github.com/daviderestivo/homebrew-emacs-head)?

**Comment by wildwestrom** [comment]
Sure. Just make sure to link to my gitlab for the original SVG.

**Comment by daviderestivo** [comment]
> Sure. Just make sure to link to my gitlab for the original SVG.

I'll do it ... thanks.

**Pull request closed without merging**
