### PR TITLE
unconditionally provide support of certain features

### PR DESCRIPTION
**Pull request by d12frosted**
- gnutls
- librsvg
- libxml2
- little-cms2
- dynamic modules
- multicolor fonts

### CODE REVIEW

**Comment by d12frosted** [comment]
Let me share some rationale behind this change. 

I don't have options usage statistic (from the moral point of view, it's even good). But I don't think that someone really disables these things. I don't see how it can hurt someone having support for dynamic modules, rsvg or gnutls. If it does - please let me know and I will consider reverting some of the options. But keep in mind that my plan is to decrease amount of available options, so the formula is simpler to maintain.

cc @daviderestivo

**Comment by cilia** [comment]
gnutls, librsvg, by default yes. But is it possible to have the option not to install libxml2, little-cms2, dynamic modules, and multicolor fonts?

**Comment by d12frosted** [comment]
@cilia sure, can you please share reasons not to enable them?

**Comment by cilia** [comment]
This might be opinionated but we're talking about Emacs anyway :)

- libxml2: how many people use it _on a Mac_ for things like eww or EPUB reader?
- multicolor fonts: isn't this removed for Mac by default because Unix/Linux doesn't support it yet? It may be included in future Emacs version but not in the current 26.3, and I guess not many people needs emoji in their Emacs.
- little-cms2: I assume this is related to multicolor fonts.
- dynamic modules: this is not enabled by default in official Emacs so why here, and certainly not a must for many (e.g. beginner/intermediate users, those who just want to use Emacs as a text editor).

My point is it'd be better to have options instead of being given a relatively bloated Emacs without choice. Thanks.

**Comment by d12frosted** [comment]
> This might be opinionated but we're talking about Emacs anyway :)

Haha, indeed. It's Emacs land 😸 These kind of questions are always debatable.

/Apologies for the long answer/

I agree with all your points. Let me now share my perspective with one simple question - does it hurt anyone if these are enabled and can't be disabled? Apart from having a little bit longer compilation time (e.g. additional dependency and patch application), though the difference is so small that I don't even notice it.

Not having an option for these things makes it easier to maintain formula. Apart from `brew` disliking options and breaking them time to time, having lots of compilation options (especially patches) makes it much harder to ensure that all combinations work. I value fast CI and patch fixing ease. So my strategy right now is to enable unconditionally all 'extra' stuff that does not hurt regular users. Even if user doesn't plan to use it initially, he/she can change mind without the need to recompile Emacs (great example of such feature is [system appearance change hooks][1]).

On the contrary, if a feature changes Emacs behaviour drastically or have runtime tradeoffs, it does make sense leave decision to the user. Examples:

- `no-titlebar` changes UI, which can't be controlled via lisp AND it also breaks `yabai` users flow.
- `xwidgets` is a cool thing, but it's huge and it used to conflict time to time, so it's dangerous to unconditionally enable it. 
- `debug` affects runtime
- `x11` or `cocoa` or even nothing is a real choice that can be made only by users.

On the other hand, `mailutils`, `dbus` and `ctags` are optional. I am yet to better understand their implication on the user. 🤷 

I also think about breaking formula into 3: `emacs-plus`, which installs release version (e.g. 26), `emacs-plus@27` and `emacs-plus@28`. But this is topic for another thread haha. Unless someone wants me to elaborate.

> My point is it'd be better to have options instead of being given a relatively bloated Emacs without choice. Thanks.

I also do value this approach 😸 So here I am trying to balance common sense and maintenance cost. But I am not a tyrant, so if someone has strong feelings about any of the options, I can change my mind 😸 But I need elaboration.

I know that I've posted a wall of text, but I would really love to hear what you think @cilia ! 

  [1]: https://github.com/d12frosted/homebrew-emacs-plus/tree/b422ccfc820b542e1a8d505710566c1a03aa872c#system-appearance-change

**Comment by cilia** [comment]
Thanks for the detailed feedback. I understand that as the main maintainer you want to make the quality and optionality of the package affordable, which mainly comes down to the cost/ease of maintaining. That's the balancing act you need to make, while we as users can provide feedback. And we thank you for your effort and time put into this.

Besides (somewhat subjective) justification for individual options/extensions, I think it's less debatable that we all come to love Emacs because it's an extensible and customizable piece of software such that people have the options to configure it in whatever way works best for them. I'll pause here and let others weigh in.

**Pull request merged**
