### PR TITLE
emacs-plus@29: inject PATH variable into Info.plist file

### PR DESCRIPTION
**Pull request by d12frosted**
The core issue here is environment in which
macOS starts applications from Finder/Docker/Spotlight/etc. This
change mostly helps users of `native-comp` feature (e.g. #378), but
it also should help other users as well ([see this comment][1])

[1]: https://github.com/d12frosted/homebrew-emacs-plus/issues/414#issuecomment-957166631

### CODE REVIEW

**Comment by d12frosted** [comment]
Will merge it on Wednesday unless someone reports issues.

**Comment by gildo** [comment]
hi @d12frosted, is this patch removing the support to brew service from emacs-29?

**Comment by d12frosted** [comment]
@gildo no, this simply injects `PATH` variable value to `Info.plist` file as the title says. You can read more about this feature in [the separate section of readme file](https://github.com/d12frosted/homebrew-emacs-plus#injected-path). Why do you think that it's related to `brew services`? And most importantly, why do you think I am removing support?

**Comment by roman-rudakov** [comment]
@d12frosted as far as I can see, the `def plist` section is removed, and when I build emacs-plus@29 I don't see `emacs-plus@29` in the `brew services list` anymore.

**Comment by d12frosted** [comment]
@roman-rudakov see https://github.com/d12frosted/homebrew-emacs-plus/pull/467

**Pull request merged**
