### PR TITLE
Fix native-comp .eln file globbing

### PR DESCRIPTION
**Pull request by daviderestivo**
Since .eln files inside "native-lisp" are now split into folders then the globbing patter has to be adjusted

### CODE REVIEW

**Comment by d12frosted** [comment]
🤔 my hack didn't work haha. Let me cherry pick on https://github.com/d12frosted/homebrew-emacs-plus/pull/337

**Comment by d12frosted** [comment]
But, @daviderestivo it's wonderful that you sent this! I have just opened https://github.com/d12frosted/homebrew-emacs-plus/issues/340 😅 

Thank you very much ;)

**Comment by d12frosted** [comment]
Ok, that worked. Thank you very much @daviderestivo 💯 

Please leave this branch open, I want to fix CI for cases when you open PRs directly from `emacs-plus` and not from a fork.

**Comment by daviderestivo** [comment]
Considering how much inspiration and help I received from you this is the bare minimum 🙂.

**Comment by daviderestivo** [comment]
> Please leave this branch open, I want to fix CI for cases when you open PRs directly from `emacs-plus` and not from a fork.

Sure 🙂. Have a nice day.

**Comment by d12frosted** [comment]
@daviderestivo thank you very much! have a great day too 🎉

**Pull request closed without merging**
