### PR TITLE
fix broken no-title-bar patch

### LINKED ISSUE #376: Broken master due to patch conflct
See CI that is red. Unfortunately I can't address this issue in adequate time frame, so I would appreciate a PR that fixes build 🙏

cc @aaronjensen maybe you want to take a look? 🙃

### PR DESCRIPTION
**Pull request by tsuu32**
fixes #376

This patch fixes broken patch and also simplifies original patch.

### CODE REVIEW

**Comment by cmacrae** [comment]
I'd already opened #377

**Comment by tsuu32** [comment]
@cmacrae Thanks mention it.
I don't care my PR will be closed.

**Review by d12frosted — APPROVED** [review]
Looks good. Let's wait for CI.

**Comment by d12frosted** [comment]
Thank you @tsuu32 for your contribution!

**Pull request merged**
