### PR TITLE
Remove ns-drawing patches

### PR DESCRIPTION
**Pull request by aaronjensen**
These are now in `emacs-26` and `master`

### CODE REVIEW

**Comment by d12frosted** [comment]
I didn't find any information (maybe I just missed it) in the Emacs devel list, but will there be a new Emacs 26 release with this fix?

**Comment by shuxiao9058** [comment]
see https://github.com/emacs-mirror/emacs/commit/6217746dd64b43a2a2b3b66ab50cfbbfc984f36c

**Comment by d12frosted** [comment]
@shuxiao9058 by release I meant something like https://ftp.gnu.org/gnu/emacs/

**Comment by shuxiao9058** [comment]
Yes, the tarball is not update yet.

**Comment by d12frosted** [comment]
I've checked it locally. Works as expected 😸 Thank you @aaronjensen !

I will deal with other options tomorrow.

**Pull request merged**
