### PR TITLE
Rename configure nativecomp flags

### PR DESCRIPTION
**Pull request by shuxiao9058**
see https://github.com/emacs-mirror/emacs/commit/42fc752a14b23be95f02b598930f13a96883d3a0

### CODE REVIEW

**Review by d12frosted — APPROVED** [review]
Thanks a lot! Cherry-picked first commit as fb629ff. Others look good as well, will cherry-pick them later when CI passes.

**Comment by shuxiao9058** [comment]
always failed, I will try again later.

**Comment by shuxiao9058** [comment]
> X11 is just plain broken right now 😅 I will try to do something about that.

I have pushed a new commit, but also failed, it seems that the x11 error.

**Comment by d12frosted** [comment]
@shuxiao9058 Thanks for the attempts 😸 Do you use `--with-x11`?

**Comment by d12frosted** [comment]
I played around with `gtk+3` (added it as dependency), it didn't work, I got errors saying that header files not found. Played a little bit with library path and other variables, didn't help.

**Comment by d12frosted** [comment]
Your initial change was merged, and since x11 is a separate concern, closing this PR. Thanks for your effrot!

**Pull request closed without merging**
