### PR TITLE
add native-comp-branch option

### LINKED ISSUE #187: native-comp branch option
The native compiling is a amazing feature to improve the Emacs performance. I'd like get an option to build this branch. Thanks!

https://github.com/emacs-mirror/emacs/tree/feature/native-comp

### PR DESCRIPTION
**Pull request by d12frosted**
fixes #187

### CODE REVIEW

**Comment by d12frosted** [comment]
Oh well, I can't test it locally now. So... power of CI?

**Comment by taigacute** [comment]
@d12frosted  i saw you add this option `with-native-comp-branch` does  `emacs-plus`it support? i found this pr can't build error on CI text..

**Comment by d12frosted** [comment]
No, `emacs-plus` doesn't support it yet. Initially I didn't figure out how to build it. Apparently [this][1] can help. 

  [1]: https://github.com/d12frosted/homebrew-emacs-plus/issues/187#issuecomment-591845157

**Comment by d12frosted** [comment]
It becomes too much hassle.

**Comment by agzam** [comment]
Has anyone built it successfully? I've wasted two days trying to get it right. Darn thing takes forever to compile. I have failed to build it with Cocoa. I need GUI, I can't use terminal only Emacs. Are things really that fast as people claim them to be? It it worth it going through the hassle?

**Comment by d12frosted** [comment]
Oh yeah, it takes so much time to compile everything. For me it starts with 105 minutes to compile `gcc` with `jit` support.

It seems that for some people [these instructions][1] worked fine.

Regarding your question about speed - I am also curious, but never succeeded to build it 😭 

  [1]: https://github.com/d12frosted/homebrew-emacs-plus/issues/187#issuecomment-667684152

**Comment by CarlQLange** [comment]
I successfully built and use it, yeah (following the instructions I posted - [these](https://github.com/d12frosted/homebrew-emacs-plus/issues/187#issuecomment-673917837) should also work). Honestly I haven't seen a lot of improvements in terms of speed, but I switched from Spacemacs to Doom around the same time so it's hard to know for sure. In any case the benchmarks definitely show a huge improvement. Whether that translates to real-life improvements... maybe?

**Comment by russell** [comment]
I have brushed up this branch to make it compile, that's not to say it's actually working yet.  But should i make a WIP PR just so that if someone else wants to try they can?  I think the current issues I'm facing are related to upstream bugs.  It seems that the binary storage location handling is different when compiling with NS vs without.

**Comment by CarlQLange** [comment]
I believe we are waiting on this PR https://github.com/Homebrew/homebrew-core/pull/59134 (or actually, this one? bit weird that they would just create a new one: https://github.com/Homebrew/homebrew-core/pull/60338) to be merged into Brew so that we have a gcc-with-jit-enabled to build with.

**Comment by d12frosted** [comment]
😿 

```
configure: error: Installed libgccjit has failed passing the smoke test.
You can verify it yourself compiling:
<https://gcc.gnu.org/onlinedocs/jit/intro/tutorial01.html>.
Please report the issue to your distribution.
Here instructions on how to compile and install libgccjit from source:
<https://gcc.gnu.org/wiki/JIT>.
```

**Comment by CarlQLange** [comment]
I got this issue as well when compiling from scratch on linux. I wish I could remember my fix - I think I just picked a different emacs commit to build from from a few days prior...

**Comment by d12frosted** [comment]
It seems that I need to configure include path. Checkout my latest commit. Still doesn't work though :D

**Comment by d12frosted** [comment]
Now I get this:

```
Last 15 lines from /Users/d12frosted/Library/Logs/Homebrew/emacs-plus-local/02.configure:
checking for X... libraries /usr/X11/lib, headers /usr/X11/include
checking AppKit/AppKit.h usability... no
checking AppKit/AppKit.h presence... yes
configure: WARNING: AppKit/AppKit.h: present but cannot be compiled
configure: WARNING: AppKit/AppKit.h:     check for missing prerequisite headers?
configure: WARNING: AppKit/AppKit.h: see the Autoconf documentation
configure: WARNING: AppKit/AppKit.h:     section "Present But Cannot Be Compiled"
configure: WARNING: AppKit/AppKit.h: proceeding with the compiler's result
configure: WARNING:     ## ------------------------------------ ##
configure: WARNING:     ## Report this to bug-gnu-emacs@gnu.org ##
configure: WARNING:     ## ------------------------------------ ##
checking for AppKit/AppKit.h... no
configure: error: The include files (AppKit/AppKit.h etc) that
are required for a Nextstep build are missing or cannot be compiled.
Either fix this, or re-configure with the option '--without-ns'.
```

**Comment by d12frosted** [comment]
The same error as here :) https://gist.github.com/AllenDang/f019593e65572a8e0aefc96058a2d23e#gistcomment-3412087

Trying clagn as `L` and `I` options didn't work

**Comment by CarlQLange** [comment]
Wow, I'm surprised you can somehow build with clang and have it still work, I don't really understand how that works!

I haven't seen the AppKit issue before sadly. I wonder if it's just a symlink missing somewhere.

**Comment by CarlQLange** [comment]
Ah, the issue mentions different GCC versions which sparked a memory. I think I also had to tweak the version of libgcc I was building with. The version I have installed now is 

```
libgccjit0/focal,now 10.2.0-5ubuntu1~20.04 amd64 [installed]
  GCC just-in-time compilation (shared library)
libgccjit-10-dev/focal,now 10.2.0-5ubuntu1~20.04 amd64 [installed]
  GCC just-in-time compilation (development files)
```

which I assume is the one I built with.

**Comment by d12frosted** [comment]
🤔 But I am getting it dynamically

```ruby
      gcc_ver = Formula["gcc"].any_installed_version
      gcc_ver_major = gcc_ver.major
      gcc = Formula["gcc"].opt_bin/"gcc-#{gcc_ver_major}"

      ENV["CFLAGS"] = "-I#{Formula["gcc"].include} -I#{Formula["libgccjit"].include}"
      ENV["LDFLAGS"] = "-L#{HOMEBREW_PREFIX}/lib/gcc/#{gcc_ver_major} -I#{Formula["gcc"].include} -I#{Formula["libgccjit"].include}"
      ENV["LIBRARY_PATH"] = "#{HOMEBREW_PREFIX}/lib/gcc/#{gcc_ver_major}:${LIBRARY_PATH:-}"
```

**Comment by d12frosted** [comment]
Nice, I think we are getting closer:

```
In file included from emacs.c:68:
./bignum.h:25:10: fatal error: 'gmp.h' file not found
#include <gmp.h>
```

**Comment by CarlQLange** [comment]
Sorry, no idea :) Let me just post the relevant bit of the flatpak I eventually got building as well, in case it's somehow helpful.

```
	{
            "name": "libgccjit",
	    "buildsystem": "autotools",
	    "config-opts": [
		"--with-linker-hash-style=gnu",
		"--enable-checking=release",
		"--enable-host-shared",
		"--enable-languages=jit",
		"--enable-static",
		"--disable-bootstrap",
		"--disable-gcov",
		"--disable-libada",
		"--disable-libgomp",
		"--disable-liboffloadmic",
		"--disable-libquadmath",
		"--disable-libquadmath-support",
		"--disable-libsanitizer",
		"--disable-libssp",
		"--disable-libstdcxx",
		"--disable-libvtv",
		"--disable-lto",
		"--disable-multilib",
		"--disable-shared"
	    ],
            "sources": [
                {
                    "type": "git",
                    "url": "git://gcc.gnu.org/git/gcc.git",
		    "tag": "releases/gcc-10.2.0"
                }
            ],
	    "cleanup": [
		"/include",
		"/lib/debug",
		"/share",
		"/libexec",
		"*.la"
	    ]
        },
        {
            "name": "emacs",
            "buildsystem": "autotools",
            "config-opts": [
                "--with-gnutls",
		"--with-nativecomp",
		"--with-modules",
		"--with-jansson",
		"--with-pgtk",
		"--with-zip",
		"--with-xwidgets"
            ],
            "sources": [
                {
		    "type": "git",
                    "url": "https://github.com/fejfighter/emacs.git",
		    "branch": "pgtk-nativecomp"
                },
                {
                    "type": "patch",
                    "path": "appdata-releases.patch"
                },
                {
                    "type": "patch",
                    "path": "appdata-launchable.patch"
                },
                {
                    "type": "patch",
                    "path": "appdata-content-rating.patch"
                },
                {
                    "type": "patch",
                    "path": "appdata-screenshot-size.patch"
                },
                {
                    "type": "patch",
                    "path": "appdata-name.patch"
                },
	        {
                    "type": "patch",
                    "path": "desktop-rename.patch"
                }
            ],
            "cleanup": [
		"/share/icons/hicolor/scalable/apps/emacs.ico",
                "/share/icons/hicolor/scalable/mimetypes/emacs-document.svg",
                "/share/icons/hicolor/scalable/mimetypes/emacs-document23.svg"
            ]
        }
```

**Comment by d12frosted** [comment]
I've managed to build with the latest commit, but running fails:

```
λ /usr/local/Cellar/emacs-plus-local/28.0.50/Emacs.app/Contents/MacOS/Emacs 
emacs: dlopen(/usr/local/Cellar/emacs-plus-local/28.0.50/Emacs.app/Contents/MacOS/../native-lisp/28.0.50-x86_64-apple-darwin19.5.0-af8a01811c8f51cae61acd918258fffe/lisp-mode-0189ba85598c041b7504f0a916c04219-1738806322de892570d69dfc55b437c2.eln, 1): image not found
```

And indeed, there is no `native-lisp` in the `Emacs.app`. Will continue digging (though a little bit later).

**Comment by CarlQLange** [comment]
Ah, this one is common! The lisp directory gets placed somewhere odd by the build process, but the .app expects it to be inside the app bundle. Most of the time people get around it by symlinking like so:

```
ln -s /usr/local/opt/gccemacs/share/emacs/28.0.50/lisp /Applications/Emacs.app/Contents/
```

I expect in your case the actual location of the `lisp` directory is elsewhere.

**Comment by seanfarley** [comment]
> I've managed to build with the latest commit, but running fails:
> 
> ```
> λ /usr/local/Cellar/emacs-plus-local/28.0.50/Emacs.app/Contents/MacOS/Emacs 
> emacs: dlopen(/usr/local/Cellar/emacs-plus-local/28.0.50/Emacs.app/Contents/MacOS/../native-lisp/28.0.50-x86_64-apple-darwin19.5.0-af8a01811c8f51cae61acd918258fffe/lisp-mode-0189ba85598c041b7504f0a916c04219-1738806322de892570d69dfc55b437c2.eln, 1): image not found
> ```
> 
> And indeed, there is no `native-lisp` in the `Emacs.app`. Will continue digging (though a little bit later).

I get this all the time when building emacs from source (outside of homebrew). I think it's a bug in the ns part of the build not being aware to copy that directory into the Emacs.app directory.

To fix it, I just run: `cp -r native-lisp/ nextstep/Emacs.app/Contents/ ` from the source directory.

**Comment by d12frosted** [comment]
Yep, copying that folder did the trick. However,

```
$ emacs: can't find function "F656c646f632d646f63756d656e746174696f6e2d64656661756c74_eldoc_documentation_default_0" in compilation unit /usr/local/Cellar/emacs-plus-local/28.0.50/Emacs.app/Contents/MacOS/../native-lisp/28.0.50-x86_64-apple-darwin19.5.0-af8a01811c8f51cae61acd918258fffe/eldoc-d20a5fe96630926dde4deb5e10fdceb0-415e8c9b2ea78bb21bdd6ed8a79a6e03.eln
```

**Comment by jimeh** [comment]
For non-self-contained builds, does it end up creating `Contents/MacOS/lib/emacs/<EMACS_VERSION>/native-lisp`?

In my self-contained builds I had to create the following symlinks directly in the `Contents` directory:

```
lisp -> Resources/lisp
native-lisp -> MacOS/lib/emacs/28.0.50/native-lisp
```

**Comment by seanfarley** [comment]
Hmm, not sure if this will help. But below is the script I use and the only weirdness is the copying of the `native-lisp` folder:

```bash
#!/bin/bash

set -o nounset
set -o errexit

# Configures Emacs for building native comp support
# http://akrl.sdf.org/gccemacs.html

# Installing under homebrew's opt, but could be anywhere.
#readonly GCCEMACS_PREFIX="$(realpath $(brew --prefix)/opt/gccemacs)"
readonly GCCEMACS_PREFIX="$PWD/nextstep/Emacs.app/Contents/MacOS"

readonly GCC_DIR="$(realpath $(brew --prefix)/opt/gcc)"
[[ -d $GCC_DIR ]] ||  { echo "${GCC_DIR} not found"; exit 1; }

readonly SED_DIR="$(realpath $(brew --prefix)/opt/gnu-sed)"
[[ -d $SED_DIR ]] ||  { echo "${SED_DIR} not found"; exit 1; }

readonly GCC_INCLUDE_DIR=${GCC_DIR}/include
[[ -d $GCC_INCLUDE_DIR ]] ||  { echo "${GCC_INCLUDE_DIR} not found"; exit 1; }

readonly GCC_LIB_DIR=${GCC_DIR}/lib/gcc/10
[[ -d $GCC_LIB_DIR ]] ||  { echo "${GCC_LIB_DIR} not found"; exit 1; }

export PATH="${SED_DIR}/libexec/gnubin:${PATH}"
export CFLAGS="-I${GCC_INCLUDE_DIR}"
export LDFLAGS="-L${GCC_LIB_DIR} -I${GCC_INCLUDE_DIR}"
export DYLD_FALLBACK_LIBRARY_PATH="${GCC_LIB_DIR}"

echo "Environment"
echo "-----------"
echo PATH: $PATH
echo CFLAGS: $CFLAGS
echo LDFLAGS: $LDFLAGS
echo DYLD_FALLBACK_LIBRARY_PATH: $DYLD_FALLBACK_LIBRARY_PATH
echo "-----------"

./autogen.sh

./configure \
     --prefix="${GCCEMACS_PREFIX}" \
     --enable-locallisppath="${GCCEMACS_PREFIX}/opt/gccemacs/site-lisp" \
     --with-ns \
     --with-mailutils \
     --with-cairo \
     --with-modules \
     --with-xml2 \
     --with-gnutls \
     --with-json \
     --with-rsvg \
     --with-nativecomp \
     --with-xwidgets \
     --with-harfbuzz \
     --disable-silent-rules \
     --disable-ns-self-contained
     #--without-dbus
     #--with-imagemagick
```

**Comment by nyamada** [comment]
Hate to ask -- is this dead in the water?

**Comment by d12frosted** [comment]
Non dead :) I am trying to make it building. If someone knows the reason of the probem - please helm me :) 

No ETA, cause I am busy lately :(

**Comment by seanfarley** [comment]
I can try to help out this weekend or next week, @d12frosted. It would help to know what are the configure options that should be on by default? Because I've noticed that cairo and a few other packages aren't picked up and I was wondering if I should work harder to get those packages linked.

**Comment by d12frosted** [comment]
Right now the branch builds (not sure what's wrong with CI), but I fail to run Emacs with the following error:

```
emacs: can't find function "F656c646f632d646f63756d656e746174696f6e2d64656661756c74_eldoc_documentation_default_0" in compilation unit /usr/local/Cellar/emacs-plus-local/28.0.50/Emacs.app/Contents/MacOS/../native-lisp/28.0.50-x86_64-apple-darwin19.5.0-3774a2e540142dd3c9da54d008a43f18/eldoc-d20a5fe96630926dde4deb5e10fdceb0-415e8c9b2ea78bb21bdd6ed8a79a6e03.eln
```

I build it using the following command (running in the root dir of `homebrew-emacs-plus` repository):

```bash
$ ./build 28 --with-native-comp
```

**Comment by jimeh** [comment]
@d12frosted my build script which produces a self-contained Emacs.app is working. I'm probably setting more env vars and stuff than I need, cause I haven't tried removing things until it breaks, but at the very least it does yield a working self-contained Emacs.app. Hopefully it might help with getting to the bottom of your build issues :)

From what I can tell it looks like you're not setting the `LIBRARY_PATH` environment variable, which I'm doing [here](https://github.com/jimeh/build-emacs-for-macos/blob/9223ff8e28e54390e2b847c5e46efc89c9e1c614/build-emacs-for-macos#L275-L278).

Also at Emacs runtime it should be able to locate gcc on it's own when installed via homebrew, but if not, try setting `LIBRARY_PATH` when launching Emacs. For my self-contained app I have a hacky elisp patch that sets `LIBRARY_PATH` to point at the embedded copy of gcc within Emacs.app the first time native compilation starts.

Also your `CLFAGS` and `LDFLAG` values are slightly different than what I'm setting them to. Again though, I suspect I don't need some of them in my script, but it works so I've just left alone... lol

**Comment by iwahbe** [comment]
I was playing around with this. It looks like emacs builds correctly, and is usable after the `make` but before the `make install` step. This can be verified by adding puts `./src/emacs --batch --eval '(message \"%s\" comp-eln-load-path)'` and then `system "false"` after `system make`.

**Comment by iwahbe** [comment]
I just made a build script that produces a self contained `Emacs.app`. I don't think you can get much simpler then this. 
<details>
  <summary>
Click to expand!
</summary>

```bash
#!/usr/bin/env bash

cflags () {
    export CFLAGS="-$1$2 $CFLAGS"
}
cflags I /usr/local/opt/gcc/include
cflags I /usr/local/opt/libgccjit/include 
cflags I /usr/local/opt/gmp/include 
cflags I /usr/local/opt/jpeg/include

ldflags () {
    export LDFLAGS="-$1$2 $LDFLAGS"
}

ldflags L /usr/local/lib/gcc/10 
ldflags I /usr/local/opt/gcc/include 
ldflags I /usr/local/opt/libgccjit/include 
ldflags I /usr/local/opt/gmp/include 
ldflags I /usr/local/opt/jpeg/include

./autogen.sh
./configure --with-nativecomp \
    --with-imagemagick \
    --with-modules \
    --with-rsvg \
    --with-xwidgets \
    --with-ns \
    --prefix="$PWD/nextstep/Emacs.app/Contents/MacOS" \
    --enable-locallisppath="${PWD}/nextstep/Emacs.app/Contents/MacOS"
make --jobs=16 NATIVE_FAST_BOOT=1
cp -r lisp nextstep/Emacs.app/Contents/Resources/
cp -r native-lisp nextstep/Emacs.app/Contents
make install --jobs=16
```

</details>

This produces a native compiled binary. Excepting the `./configure` flags, every line is necessary.

**Comment by WarFox** [comment]
Thanks @iwahbe this worked for me on my macOS Catalina.
Simple and straight forward

**Comment by nyamada** [comment]
Alas, the simple build script fails for me under Mojave -- lots of errors like this -- 

```ld: warning: ignoring file ../lib/libgnu.a, building for macOS-x86_64 but attempting to link with file built for macOS-x86_64
ld: warning: ignoring file ../lib/libgnu.a, building for macOS-x86_64 but attempting to link with file built for macOS-x86_64
ld: warning: ignoring file ../lib/libgnu.a, building for macOS-x86_64 but attempting to link with file built for macOS-x86_64
Undefined symbols for architecture x86_64:
  "_set_binary_mode", referenced from:
      _main in hexl-ae6d4e.o
ld: symbol(s) not found for architecture x86_64
Undefined symbols for architecture x86_64:
  "_fingerprint", referenced from:
      _main in make-fingerprint-8b977f.o
  "_rpl_getopt", referenced from:
      _main in make-fingerprint-8b977f.o
  "_rpl_memmem", referenced from:
      _main in make-fingerprint-8b977f.o
  "_rpl_optind", referenced from:
      _main in make-fingerprint-8b977f.o
  "_sha256_finish_ctx", referenced from:
      _main in make-fingerprint-8b977f.o
  "_sha256_init_ctx", referenced from:
      _main in make-fingerprint-8b977f.o
  "_sha256_process_bytes", referenced from:
      _main in make-fingerprint-8b977f.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [hexl] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [make-fingerprint] Error 1
Undefined symbols for architecture x86_64:
  "_rpl_faccessat", referenced from:
      _set_local_socket in emacsclient-ca646d.o
  "_rpl_getopt_long_only", referenced from:
      _decode_options in emacsclient-ca646d.o
  "_rpl_optarg", referenced from:
      _decode_options in emacsclient-ca646d.o
  "_rpl_optind", referenced from:
      _main in emacsclient-ca646d.o
      _fail in emacsclient-ca646d.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [emacsclient] Error 1
ld: warning: ignoring file ../lib/libgnu.a, building for macOS-x86_64 but attempting to link with file built for macOS-x86_64
ld: warning: ignoring file ../lib/libgnu.a, building for macOS-x86_64 but attempting to link with file built for macOS-x86_64
```

**Comment by d12frosted** [comment]
Ah well, locally it doesn't build because of python installation failures.

**Comment by d12frosted** [comment]
It seems that it works even in the end of `install` function. But then `brew` does some magic which breaks Emacs.

In order to reproduce, put `system "false"` somewhere in the end of `install` function, but after `make install` and `prefix.install "nextstep/Emacs.app"`. Then run

```
$ /usr/local/Cellar/emacs-plus@28/28.0.50/Emacs.app/Contents/MacOS/Emacs -Q
```

Notice that it works. But once you ask `brew` to ignore the error, it gets to post install and afterwards emacs doesn't work anymore.

**Comment by d12frosted** [comment]
Hm... I see logs like

```
=> Changing dylib ID of /usr/local/Cellar/emacs-plus-local/28.0.50/Emacs.app/Contents/native-lisp/28.0.50-x86_64-apple-darwin20.1.0-f10e7cb1f8775ac8884b227b6e51f168/abbrev-2af30c9ac0795d54ce43b6286aa259ff-a03852565cd14ed2eaa6f4159b530c2e.eln
  from /private/tmp/libgccjit-y8REGV/fake.so
    to /usr/local/opt/emacs-plus-local/Emacs.app/Contents/native-lisp/28.0.50-x86_64-apple-darwin20.1.0-f10e7cb1f8775ac8884b227b6e51f168/fake.so
```

**Comment by daviderestivo** [comment]
> It seems that it works even in the end of `install` function. But then `brew` does some magic which breaks Emacs.
> 
> In order to reproduce, put `system "false"` somewhere in the end of `install` function, but after `make install` and `prefix.install "nextstep/Emacs.app"`. Then run
> 
> ```
> $ /usr/local/Cellar/emacs-plus@28/28.0.50/Emacs.app/Contents/MacOS/Emacs -Q
> ```
> 
> Notice that it works. But once you ask `brew` to ignore the error, it gets to post install and afterwards emacs doesn't work anymore.
> 
> Well, one more step!

I'm smashing my head on this since two days :) ...

**Comment by iwahbe** [comment]
On the most recent version, this fails for me at a `SHA256 mismatch`
<details>

```bash
❯ ./build 28 --with-native-comp
==> Downloading https://homebrew.bintray.com/bottles/c-ares-1.17.1.catalina.bottle.tar.gz
Already downloaded: /Users/ianwahbe/Library/Caches/Homebrew/downloads/bcc766ef22142c2c04b122ea0f2070befdf145693edd77d92676d70af6f561b0--c-ares-1.17.1.catalina.bottle.tar.gz
==> Downloading https://homebrew.bintray.com/bottles/jemalloc-5.2.1_1.catalina.bottle.tar.gz
Already downloaded: /Users/ianwahbe/Library/Caches/Homebrew/downloads/dc9654699a1655295a1319ee956e64a6318387e860c95b5c7ed43b71af05a47d--jemalloc-5.2.1_1.catalina.bottle.tar.gz
==> Downloading https://homebrew.bintray.com/bottles/libev-4.33.catalina.bottle.tar.gz
Already downloaded: /Users/ianwahbe/Library/Caches/Homebrew/downloads/25986a407604060b345a80ce81f51c69f9632ef16de0474e2efcfc69aaf83f2e--libev-4.33.catalina.bottle.tar.gz
==> Downloading https://homebrew.bintray.com/bottles/nghttp2-1.42.0.catalina.bottle.1.tar.gz
Already downloaded: /Users/ianwahbe/Library/Caches/Homebrew/downloads/88508f0b5b6fe8f4b6ebafa4ccdf474dc326791958553871b31813a251c9a84d--nghttp2-1.42.0.catalina.bottle.1.tar.gz
==> Downloading https://homebrew.bintray.com/bottles/unbound-1.12.0_1.catalina.bottle.tar.gz
Already downloaded: /Users/ianwahbe/Library/Caches/Homebrew/downloads/17e648ea023235502b669989b07f73005cb916013c12f2054a34e606277f52da--unbound-1.12.0_1.catalina.bottle.tar.gz
==> Downloading https://homebrew.bintray.com/bottles/python%403.9-3.9.0_2.catalina.bottle.tar.gz
Already downloaded: /Users/ianwahbe/Library/Caches/Homebrew/downloads/f40ec7142538a2d124655023300e9ba1c6d01ab20656ab9908a4472e284b5b13--python@3.9-3.9.0_2.catalina.bottle.tar.gz
==> Downloading https://homebrew.bintray.com/bottles/librsvg-2.50.2.catalina.bottle.tar.gz
Already downloaded: /Users/ianwahbe/Library/Caches/Homebrew/downloads/ac42f39d9a09c89317808276df7860b16cf04130460c4c5d9d60366f4d6922b8--librsvg-2.50.2.catalina.bottle.tar.gz
==> Downloading https://homebrew.bintray.com/bottles/imagemagick-7.0.10-44.catalina.bottle.tar.gz
Already downloaded: /Users/ianwahbe/Library/Caches/Homebrew/downloads/38e739ec1cbdb9ad8ac2589520b5db025fdfd34910d245562ce38989699e82cb--imagemagick-7.0.10-44.catalina.bottle.tar.gz
==> Downloading https://raw.githubusercontent.com/d12frosted/homebrew-emacs-plus/feature/native-comp-branch/patches/emacs-2
Already downloaded: /Users/ianwahbe/Library/Caches/Homebrew/downloads/d6aa38272a9f2e6925f681c6591e896e9bdfef71409d424d1ac08f99be30daf7--fix-window-role.patch
==> Downloading https://raw.githubusercontent.com/d12frosted/homebrew-emacs-plus/feature/native-comp-branch/patches/emacs-2
Already downloaded: /Users/ianwahbe/Library/Caches/Homebrew/downloads/48f5e4e5927692c9e6ea2ccecd13440f0c4a59d305dab990c93420bbe6f555a9--system-appearance.patch
Error: SHA256 mismatch
Expected: 22b541e2893171e45b54593f82a0f5d2c4e62b0e4497fc0351fc89108d6f0084
  Actual: b4ccc981e461ac12661fc4cf0ad7211a1dcab61dccf4bd4eee49ca5f7d66c496
    File: /Users/ianwahbe/Library/Caches/Homebrew/downloads/48f5e4e5927692c9e6ea2ccecd13440f0c4a59d305dab990c93420bbe6f555a9--system-appearance.patch
To retry an incomplete download, remove the file above.
```

</details>

**Comment by d12frosted** [comment]
> I'm smashing my head on this since two days :) ...

Understand why :) 

> On the most recent version, this fails for me at a SHA256 mismatch

Just delete cached file and it will be good. Unfortunately, brew doesn't have versioning for resources. Apparently we should manually mimic it.

**Comment by daviderestivo** [comment]
@d12frosted I have opened an [issue](https://github.com/Homebrew/brew/issues/9526) on brew GitHub page. Let's see what the developers tell us ... brew uses https://www.rubydoc.info/gems/ruby-macho/ for mangling the dylibs and I suspect a bug there.

**Comment by daviderestivo** [comment]
A PR request have been created out of the opened issue: https://github.com/Homebrew/brew/pull/10075. I hope it will be merged soon :)

**Comment by daviderestivo** [comment]
@d12frosted This https://github.com/d12frosted/homebrew-emacs-plus/pull/188/commits/6ecfa3c1d04c6c0ab16e0aba326ed50bf977d744 should make the trick ;)

**Comment by d12frosted** [comment]
@daviderestivo 💯 thank you very much! adding dummy commit to fix CI

**Comment by d12frosted** [comment]
status in CI is fake! :) will test it locally and if everything ok, merge it

**Comment by d12frosted** [comment]
Yep, locally it builds, so merging!

**Comment by d12frosted** [comment]
Merged as d8247e4. CI will fail (I think), but I will tackle it later.

If you encounter any errors, please report them to this thread: https://github.com/d12frosted/homebrew-emacs-plus/issues/187

**Pull request closed without merging**
