### PR TITLE
(icons) add elrumo icons

### PR DESCRIPTION
**Pull request by d12frosted**
Following #303

### CODE REVIEW

**Comment by d12frosted** [comment]
@elrumo can you please review this PR? 😸 Please let me know if you are fine with the names I used for these icons.

**Comment by d12frosted** [comment]
Icon is successfuly downloaded, so ignore failing builds, they are not replated :(

**Comment by daviderestivo** [comment]
@d12frosted if is fine for you I would like to add them to emacs-head 😄

**Comment by d12frosted** [comment]
I am fine. Plese ask the author - @elrumo 😸

**Comment by daviderestivo** [comment]
@elrumo: is it ok for you?

**Comment by elrumo** [comment]
@Sureadaviderestivo sure! No problem 😁

**Comment by daviderestivo** [comment]
> @Sureadaviderestivo sure! No problem 😁

Thanks :)

**Comment by d12frosted** [comment]
🎉 now we will be synced in terms of icons @daviderestivo :D 

thanks @elrumo

**Comment by daviderestivo** [comment]
> 🎉 now we will be synced in terms of icons @daviderestivo :D 

Yup 🤣

**Pull request merged**
