### PR TITLE
Update xwidgets_webkit_in_cocoa.patch

### PR DESCRIPTION
**Pull request by fuxialexander**
Resolve conflict on HEAD

### CODE REVIEW

**Comment by fuxialexander** [comment]
Should solve https://github.com/d12frosted/homebrew-emacs-plus/issues/146
Not tested on pdumper branch, but since it's already merged to master I guess it's fine.

**Comment by zachdaniel** [comment]
Could this be merged? If so, that would definitely save me some time :)

**Comment by d12frosted** [comment]
Sorry for the delay with this patch.

Two comments:

1. SHA is not the right one, should be: `bd614add2ca3b0da940521116b8b78f605213229747502c2159a728db5ac82d3`.
2. It doesn't apply on master cleanly.

@fuxialexander how is it going with the patch on the upstream? :)

**Comment by JSpenced** [comment]
Is there a fix for this coming? Also, when I open an org-file it just freezes and I am guessing might be due to a rendering problem. Is there a way to install previous heads? I forgot to pin the package in brew so it updated.

**Comment by xeijin** [comment]
@fuxialexander any luck with this one?

**Comment by d12frosted** [comment]
Build was fixed in #166. So closing this.

**Pull request closed without merging**
