### PR TITLE
Replaces 'Install' with 'Instead,'

### PR DESCRIPTION
**Pull request by pachevjoseph**

### CODE REVIEW

**Comment by d12frosted** [comment]
Haha. Thank you very much for this typo fix.

Ignore failing tests.

**Comment by d12frosted** [comment]
@pachevjoseph do you mind if I will try to fix tests in your PR?

It seems that I misunderstood meaning of one of the environment variables provided by GitHub workflows and so any PR is broken.

**Comment by pachevjoseph** [comment]
> @pachevjoseph do you mind if I will try to fix tests in your PR?
> 
> It seems that I misunderstood meaning of one of the environment variables provided by GitHub workflows and so any PR is broken.

I have with that at all. Please go ahead. Your package was super helpful for me trying emacs out.

**Comment by d12frosted** [comment]
Ah, never mind. Will do it with my second account. Should be easy to fix though.

In any case, thank you very much for this fix and for your kind words! Have a nice day!

**Comment by d12frosted** [comment]
Your commit was cherry-picked (5a2f72b366d93d011e60839e2d8a54ad3dc70373) so you can safely remove your branch! ❤️

**Pull request closed without merging**
