### PR TITLE
Update no-title-bar-patch for Emacs 25.2

### PR DESCRIPTION
**Pull request by aaronjensen**
This patch works w/ Emacs 25.2

### CODE REVIEW

**Comment by d12frosted** [comment]
Hey @aaronjensen,

I have merged #38 and it conflicts with your PR (sorry about that). I don't see any real difference between patches, but I like your changes to readme and formulae itself (better documentation) 😸 

In case I haven't missed anything, I'll fix conflicts manually. 

Let me know what you think.

**Comment by aaronjensen** [comment]
@d12frosted that sounds great, no problem at all. You should be able to just cherrypick 4d21460

**Comment by d12frosted** [comment]
Thanks! I have cherry picked that commit.

**Comment by braham-snyder** [comment]
My apologies for my redundant PR--I should have double-checked the existing PRs before making a new one. Great to hear about `undecorated`!

**Pull request closed without merging**
